NUM_OF_FLOORS = 15
NUM_OF_ELEVATORS = 3

SECONDS_PER_FLOOR = 0.5
STOP_TIME = 2



FLOOR_IMAGE_PATH  = "/home/mefathim89/Downloads/2458990.jpg"
ELEVATOR_IMAGE_PATH = "/home/mefathim89/Downloads/elv.png"

SCREEN_HEIGHT = 600
SCREEN_WIDTH = 500
FLOOR_IMAGE_HEIGHT = SCREEN_HEIGHT // NUM_OF_FLOORS
FLOOR_WIDTH = 100
FLOOR_SPACER_HEIGHT = 7
MID_SPACER = FLOOR_SPACER_HEIGHT//2 
COLOR = (200,200,200)
LINE_COLOR = (0,0,0)
BUTTON_COLOR = (0,255,0)

ELEVATOR_HEIGHT = FLOOR_IMAGE_HEIGHT
ELEVATOR_WIDTH = ELEVATOR_HEIGHT

NUM_FLOOR_COLOR = (0,0,0)
LOCATION_X_NUM_FLOOR = 60
LOCATION_Y_NUM_FLOOR = FLOOR_IMAGE_HEIGHT*0.3
BLACK = (0,0,0)